
# "Config" is the reserved word which to mark the env

[Config]
package="com.mckj.module.wifi.gen"
dir= "../src/main/java"
#author= "[Author name or empty]"
#nameKey="nm"
#typeKey="t"
#commentKey="c"

# "Params" is the reserved word which to define the analyse sub params of a event
# param=alias, the alias use to write this toml

# the "c" is reserved word to param
[Params]
what="w"
where="wh"
when="wn"
from="f"
type="t"


# the events
# [event_name]
# c="the event comment"
# act="the act params comment"
# content=""    if comment is empty , ignore

[home_set_click]
c="主页_设置按钮_点击"

[set_functionset_click]
c="设置_功能设置按钮_点击"

[set_aboutus_click]
c="设置_关于我们按钮_点击"

[home_wifispeedup_click]
c="主页_一键加速_点击"

[home_speedtest_click]
c="主页_网络测试_点击"

[home_safetycheck_click]
c="主页_安全检测_点击"

[home_signalboost_click]
c="主页_信号增强_点击"

[speedtest_show]
c="网络测试_页面_展示"

[safetycheck_show]
c="安全检测_页面_展示"

[signalboost_show]
c="信号增强_页面_展示"

[speedtest_back_click]
c="网络测试_返回按钮_点击"

[speedtest_stoptest_click]
c="网络测试_停止测速_点击"

[safetycheck_back_click]
c="安全检测_返回按钮_点击"

[signalboost_back_click]
c="信号增强_返回按钮_点击"

[home_wifi_lottery_phone_click]
c="幸运抽手机_点击"

[home_wifi_network_speedup_click]
c="网络加速_点击"

[home_wifi_clean_speedup_click]
c="清理加速_点击"

[home_wifi_wechat_speedup_click]
c="微信加速_点击"

[home_wifi_video_speedup_click]
c="视频加速_点击"

[home_wifi_switch_click]
c="切换wifi_点击"

[wifilist_getpop_show]
c="已连接wifi_下方弹框_展示"

[wifilist_get_click]
c="已连接wifi_点击"

[wifilist_no_click]
c="未连接wifi_点击"

[wifilist_getpop_close_click]
c="已连接wifi_下方弹框_取消按钮_点击"

[wifilist_getpop_wifispeedup_click]
c="已连接wifi_一键加速_点击"

[wifilist_getpop_speedtest_click]
c="已连接wifi_网络测试_点击"

[wifilist_getpop_safetycheck_click]
c="已连接wifi_安全检测_点击"

[wifilist_getpop_signalboost_click]
c="已连接wifi_信号增强_点击"

[wifilist_getpop_hotspotinfo_click]
c="已连接wifi_热点信息_点击"

[wifilist_getpop_accusal_click]
c="已连接wifi_举报钓鱼_点击"

[wifilist_getpop_disconnect_click]
c="已连接wifi_断开网络_点击"

[wifilist_nopop_get_click]
c="未连接wifi_输入密码弹框_确认按钮_点击"

[wifilist_nopop_close_click]
c="未连接wifi_输入密码弹框_取消按钮_点击"

[wifilist_nopop_show]
c="未连接wifi_输入密码弹框_展示"

[widget_long_create]
c="小工具设置成功"

[widget_long_icon_click]
c="小工具三格-桌面图标-点击使用"

[widget_long_system_show]
c="弹出小工具设置_展示"

[notify_show]
c="常驻通知栏-展示"

[notify_home_click]
c="常驻通知栏-公共区域-点击（进入app首页）"

[notify_speedup_click]
c="常驻通知栏-一键加速-点击"

[home_location_click]
c="主页_定位获取_点击"

[home_location_success]
c="主页_定位获取_成功"

[A_pop_reqpermission_show]
c="弹出权限请求"

[A_pop_reqpermission_allpass]
c="权限全通过"

[news_show]
c="新闻_列表_展示"

[news_info_show]
c="新闻_详细页_展示"

[news_ad_show]
c="新闻_列表_广告_展示"

[news_ad_click]
c="新闻_列表_广告_点击"

[wifi_videoad_show_all]
c="wifi_视频广告_展示_总和"

[wifi_msgad_show_all]
c="wifi_插屏广告_展示_总和"

[home_rubnet_click]
c="主页_防蹭网_点击"

[home_sharing_click]
c="主页_热点分享_点击"