
# "Config" is the reserved word which to mark the env

[Config]
package="com.mckj.appsenceslib.gen"
dir= "../src/main/java"
#author= "[Author name or empty]"
#nameKey="nm"
#typeKey="t"
#commentKey="c"

# "Params" is the reserved word which to define the analyse sub params of a event
# param=alias, the alias use to write this toml

# the "c" is reserved word to param
[Params]
what="w"
where="wh"
when="wn"
from="f"
type="t"


# the events
# [event_name]
# c="the event comment"
# act="the act params comment"
# content=""    if comment is empty , ignore


[level_show]
c="落地页_页面_展示"
t="来源"

[wifi_level_backButtonTop_click]
c="落地页_顶部返回按钮_点击_左边"
t="来源"

[wifi_level_backButtonMiddle_click]
c="落地页_居中返回按钮_点击"
t="来源"

[wifi_level_backButtonright_click]
c="落地页_右上角返回按钮_点击"
t="来源"

[level_guide_click]
c="wifi_落地页_功能引导_点击"
t="来源"

[level_ad_show]
c="落地页_广告_展现"
t="来源"

[level_ad_click]
c="落地页_广告_点击"
t="来源"

[level_before_ad_show]
c="落地页前_广告_展示"
t="来源"

[level_before_ad_click]
c="落地页前_广告_点击"
t="来源"

[level_before_ad_close]
c="落地页前_广告关闭按钮_点击"
t="来源"

[level_back_ad_show]
c="落地页后_视频广告_展示"
t="来源"

[level_back_ad_click]
c="落地页后_视频广告_点击"
t="来源"

[level_back_ad_close]
c="落地页后_广告_关闭"
t="来源"

[home_caton_click]
c="主页_卡顿优化_点击"