
# "Config" is the reserved word which to mark the env

[Config]
#package="com.mckj.appsenceslib.gen"
package="com.mckj.sceneslib.gen"
dir= "../src/main/java"
#author= "[Author name or empty]"
#nameKey="nm"
#typeKey="t"
#commentKey="c"

# "Params" is the reserved word which to define the analyse sub params of a event
# param=alias, the alias use to write this toml

# the "c" is reserved word to param
[Params]
what="w"
where="wh"
when="wn"
from="f"
type="t"


# the events
# [event_name]
# c="the event comment"
# act="the act params comment"
# content=""    if comment is empty , ignore

[level_flash_show]
c="落地页前_动画_展示"
t="场景名称 "
f="站内外"


[level_flash_end]
c="落地页前_动画_结束"
t="场景名称"
f="站内外"


[level_show]
c="落地页_页面_展示"
t="场景名称"
f="站内外"


[level_return_click]
c="落地页_返回按钮_左上角_点击"
t="来源"

[wifi_level_backButtonTop_click]
c="落地页_顶部返回按钮_点击_左边"
t="来源"

[wifi_level_backButtonMiddle_click]
c="落地页_居中返回按钮_点击"
t="来源"

[wifi_level_backButtonright_click]
c="落地页_右上角返回按钮_点击"
t="来源"

[level_guide_click]
c="wifi_落地页_功能引导_点击"
t="来源"

[level_ad_show]
c="落地页_广告_展现"
t="场景名称"
f="站内外"

[level_ad_close]
c="落地页_广告_展现"
t="来源"

[level_ad_click]
c="落地页_广告_点击"
t="来源"

[level_before_ad_show]
c="落地页前_广告_展示"
t="来源"

[level_before_ad_click]
c="落地页前_广告_点击"
t="来源"

[level_before_ad_close]
c="落地页前_广告关闭按钮_点击"
t="来源"

[level_back_ad_show]
c="落地页后_视频广告_展示"
t="来源"

[level_back_ad_click]
c="落地页后_视频广告_点击"
t="来源"

[level_back_ad_close]
c="落地页后_广告_关闭"
t="来源"

[home_caton_click]
c="主页_卡顿优化_点击"

[speed_scan_start]
c="网络测速_扫描_开始"

[speed_scan_return_click]
c="网络测速_扫描_返回键_点击"

[speed_report_show]
c="网络测速_测速报告_展示"

[speed_red_packet_click]
c="网络测速_抢红包测速_点击"

[red_packet_scan_start]
c="抢红包测速_扫描_开始"

[red_packet_result_show]
c="抢红包测速_扫描结果_展示"

[red_packet_return_click]
c="抢红包测速_扫描_返回键_点击"

[red_packet_retest_click]
c="抢红包测速_重新测速_点击"

[permission_sys_dialog_show]
c="应用内权限弹窗展示"
w="权限名称"
f="触发功能来源"

[permission_sys_dialog_dismiss]
c="应用内权限弹窗关闭"
w="权限名称"
t="权限结果"

[permission_app_dialog_show]
c="应用内权限引导弹窗展示"
w="权限名称"
f="触发功能来源"

[permission_app_dialog_dismiss]
c="应用内权限引导弹窗结束"
w="权限名称"
t="点击结果"

[home_function_click]
c="主页_功能按钮_点击"
t="功能按钮的名称"


[kit_function_click]
c="工具箱_功能按钮_点击"
t="功能按钮的名称"



[desktop_widget_pre_pop]
c="小组件弹窗准备弹出"

[desktop_widget_pop]
c="小组件弹窗展示"

[desktop_widget_set_success]
c="小组件设置结果"
t = "组件设置结果"

[O_desktop_widget_click]
c="桌面小组件按钮点击"
t = "调起结果"

[exit_confirm_popup_show]
c="退出优化_二次确认弹窗_展示"
f = "对应场景"

[exit_confirm_popup_click]
c="退出优化_二次确认弹窗_点击"
f = "对应场景"
t = "Keep或者Stop"

[optimize_level_show]
c="优化结果"
f = "对应场景"
t = "清理结果差"

[scan_junk_flash_show]
c="垃圾文件_扫描动画_展示"
f = "对应任务"
t = "耗时"
w = "垃圾大小"
wh = "场景来源，站外站内"

[optimize_level_click]
c="扫描结果页_点击清理"
t = "是否自动点击"

[level_msg_show]
c="落地页信息流_广告_展示"









[notice_clean_show]
c="通知清理_清理_展示"

[notice_clean_all_click]
c="通知清理_清理_点击"

[set_volume_click]
c="智能音量_点击"
t="类型"

[set_volume_show]
c="智能音量_展示"

[dust_speaker_start_click]
c="声波除尘_扬声器_开始除尘_点击"

[dust_receiver_click]
c="声波除尘_听筒除尘_点击"

[dust_receiver_start_click]
c="声波除尘_听筒除尘_开始除尘_点击"

[scan_insert_ad_show]
c="插屏广告展示"

[scan_insert_ad_colse]
c="插屏广告关闭"

[mask_show]
c="首页遮罩_展示"
f = "场景类型"

[mask_click]
c="首页遮罩_点击"
t="点击类型"
f = "场景类型"

[level_return_close]
c="清理落地页_点击返回"

[level_recommend_click]
c="清理落地页_点击功能引导"
t="功能名"

[level_recommend_click_auto]
c="清理落地页_自动功能跳转"
t="功能名"

[exit_confirm_threaten_click]
c="退出优化_威胁页_点击"
t="功能名"

[ad_msg_threaten_show]
c="威胁结果页_信息流展示"
f = "功能名"
t = "应用内或者应用外"

[exit_confirm_threaten_show]
c="退出优化_威胁页_展示"
f = "功能名"

[recommend_pool_protect]
c="功能推荐池_保护"
t="类型"

[recommend_function_protect]
c="功能_保护"
t="类型"

[recommend_card_show]
c="功能推荐卡片_展示"
t="功能名称"

[recommend_card_click]
c="功能推荐卡片_点击"
t="类型"



[set_accounting_click]
c="记账_点击"
t="类型"

[set_accounting_show]
c="记账_展示"

[set_monitor_click]
c="网络监控_点击"

[set_monitor_show]
c="网络监控_展示"

[set_countdown_click]
c="倒数日_点击"
t="类型"

[set_countdown_show]
c="倒数日_展示"

[set_font_click]
c="字体放大_点击"
t="类型"

[set_font_show]
c="字体放大_展示"