
# "Config" is the reserved word which to mark the env

[Config]
package="com.mckj.module.cleanup.gen"
dir= "../src/main/java"
#author= "[Author name or empty]"
#nameKey="nm"
#typeKey="t"
#commentKey="c"

# "Params" is the reserved word which to define the analyse sub params of a event
# param=alias, the alias use to write this toml

# the "c" is reserved word to param
[Params]
what="w"
where="wh"
when="wn"
from="f"
type="t"


# the events
# [event_name]
# c="the event comment"
# act="the act params comment"
# content=""    if comment is empty , ignore

[clean_show]
c="首页_展示"

[home_clean_click]
c="主页_一键清理按钮_点击"

[home_iconclean_click]
c="主页_一键清理图标_点击"

[home_clean_auto_scan]
c="主页_一键清理自动扫描次数"

[home_clean_clean_click]
c="主页_立即清理_点击"

[home_clean_iconclean_click]
c="主页_立即清理图标_点击"

[home_detail_click]
c="主页_清理详细页_点击"

[home_speedup_click]
c="主页_手机加速_点击"

[home_cooldown_click]
c="主页_手机降温_点击"

[home_wechatclean_click]
c="主页_微信清理_点击"

[home_savepower_click]
c="主页_超级省电_点击"

[home_network_click]
c="主页_网络加速_点击"

[home_antivirus_click]
c="主页_手机杀毒_点击"

[home_smallvideo_click]
c="主页_短视频清理_点击"

[home_camera_click]
c="主页_摄像头检测_点击"

[home_qqclean_click]
c="主页_QQ清理_点击"

[home_uninstall_click]
c="主页_残留清理_点击"

[home_signal_click]
c="主页_信号优化_点击"

[home_file_click]
c="主页_文件管理_点击"

[home_setup_click]
c="主页_右上角设置_点击"
t="来源"

[home_authority_click]
c="主页_右上角权限_点击"

[home_photo_click]
c="主页_相册清理_点击"

[home_video_click]
c="主页_视频清理_点击"

[home_bigfile_click]
c="主页_大文件管理_点击"

[home_installe_click]
c="主页_安装包清理_点击"

[home_music_click]
c="主页_音乐清理_点击"

[home_zip_click]
c="主页_压缩包清理_点击"

[home_scan_start]
c="首页_扫描_开始"

[home_scan_stop]
c="首页_扫描_停止"

[home_clean_detail_click]
c="首页_一键清理_垃圾详情_点击"

[home_kit_click]
c="首页_工具箱_点击"

[home_photo_clean_click]
c="首页_相册清理_点击"


[kit_weather_click]
c="工具箱_天气_点击"

[kit_page_show]
c="工具箱_页面展示"

[kit_calendar_click]
c="工具箱_日历_点击"

[kit_traffic_click]
c="工具箱_流量使用_点击"

[kit_parameter_click]
c="工具箱_手机参数_点击"

[kit_size_click]
c="工具箱_字体大小_点击"

[kit_flashlight_click]
c="工具箱_手电筒_点击"
t="开关"

[kit_clock_click]
c="工具箱_闹钟_点击"

[kit_photo_click]
c="工具箱_相册_点击"


[photo_clean_up_guidance_show]
c="相册清理_上滑引导_展示"

[photo_clean_both_sides_guidance_show]
c="相册清理_左右划引导_展示"

[photo_clean_recycle_show]
c="相册清理_回收站引导_展示"

[photo_clean_page_up_glide]
c="相册清理_清理页面_上滑"

[photo_clean_page_both_sides]
c="相册清理_清理页面_左右划"

[photo_clean_recycle_click]
c="相册清理_回收站_点击"

[photo_clean_classify_click]
c="相册清理_相册分类_点击"

[photo_clean_thumbnail_click]
c="相册清理_缩略图_点击"

[photo_clean_thumbnail_slide]
c="相册清理_缩略图_点击"

[classify_pop_show]
c="相册分类弹窗_展示"

[classify_pop_close_click]
c="相册分类弹窗_关闭_点击"

[classify_pop_album_click]
c="相册分类弹窗_分类_点击"
t="分类名称"



[recycle_recover_click]
c="回收站_恢复_点击"

[recycle_delete_click]
c="回收站_彻底删除_点击"

[recycle_photo_preview]
c="回收站_图片_大图预览"

[recycle_auto_delete]
c="回收站_7天自动删除_删除"
t="删除张数"